/* @generated by scripts/promote-selectors.ts — do not hand-edit */
export const GENERATED_LA_SELECTORS: Record<string, string> = {
  "application_id": "input[name=\"application_id\"]",
  "passport_number": "input[name=\"passport_number\"]",
  "verify_code": "input[name=\"verify_code\"]",
};
