import type { PdfLine } from "../paper/simple-pdf.js";

/**
 * Japan paper-pack field mappings (RUN-JP-001 / RUN-JP-002).
 *
 * Japan is a paper-only channel (no online submit). This maps the canonical
 * answer set → the printable application's labelled lines. Mirrors the
 * paper template registry's COMMON_FIELDS so the rendered pack matches the
 * seeded paper_template layout.
 */

export interface JpField {
  answerKey: string;
  label: string;
  format?: "default" | "uppercase";
}

export const JP_PAPER_FIELDS: JpField[] = [
  { answerKey: "surname", label: "Surname", format: "uppercase" },
  { answerKey: "given_names", label: "Given Names", format: "uppercase" },
  { answerKey: "date_of_birth", label: "Date of Birth" },
  { answerKey: "nationality", label: "Nationality" },
  { answerKey: "passport_number", label: "Passport Number", format: "uppercase" },
  { answerKey: "passport_expiry_date", label: "Passport Expiry" },
  { answerKey: "passport_issuing_country", label: "Passport Issuing Country" },
  { answerKey: "email", label: "Email" },
  { answerKey: "phone", label: "Phone" },
  { answerKey: "intended_arrival_date", label: "Intended Arrival" },
  { answerKey: "occupation", label: "Occupation" },
  { answerKey: "visit_purpose", label: "Purpose of Visit" },
];

export const JP_PAPER_TITLE = "Japan Visa Application (Paper Pack)";

function fmt(raw: string, format?: JpField["format"]): string {
  return format === "uppercase" ? raw.toUpperCase() : raw;
}

/**
 * Build the printable lines from canonical answers. Pure — the unit-tested
 * core of the Japan paper renderer. Missing answers render as a blank line
 * (the applicant completes by hand).
 */
export function buildJpPaperLines(answers: Record<string, string>): PdfLine[] {
  const lines: PdfLine[] = [{ text: JP_PAPER_TITLE, size: 16, bold: true }];
  for (const f of JP_PAPER_FIELDS) {
    const raw = answers[f.answerKey];
    const value = raw ? fmt(raw, f.format) : "________________";
    lines.push({ text: `${f.label}: ${value}` });
  }
  lines.push({ text: "Generated by VIZA — present this pack at the consulate.", size: 9 });
  return lines;
}
