/* @generated by scripts/promote-selectors.ts — do not hand-edit */
export const GENERATED_ZA_SELECTORS: Record<string, string> = {
  "chkbox_id": "#chkbox-id",
  "ot_group_id_c0002": "input[name=\"ot-group-id-C0002\"]",
  "ot_group_id_c0003": "input[name=\"ot-group-id-C0003\"]",
  "ot_group_id_c0004": "input[name=\"ot-group-id-C0004\"]",
  "select_all_hosts_groups_handler": "#select-all-hosts-groups-handler",
  "select_all_vendor_groups_handler": "#select-all-vendor-groups-handler",
  "select_all_vendor_leg_handler": "#select-all-vendor-leg-handler",
  "vendor_search_handler": "input[name=\"vendor-search-handler\"]",
};
